services:
  - type: web
    name: company-policy-rag
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python ingest.py
    startCommand: gunicorn -w 2 -b 0.0.0.0:5000 app:app --timeout 120
    envVars:
      - key: PORT
        value: "5000"
      - key: FLASK_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: openrouter
      - key: MODEL_NAME
        value: meta-llama/llama-3.1-8b-instruct:free
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: TOP_K
        value: 5
    healthCheckPath: /health
